/*+***********************************************************************************
 * Potentials EditView: lock auto-generated fields.
 * - Opportunity Name (potentialname) is auto-synced to Project Code by backend logic.
 * - Project Code (cf_859) is generated by ProjectCodeHandler.
 * We keep fields visible and submitted, but prevent manual typing.
 *************************************************************************************/
(function () {
	if (typeof jQuery === 'undefined') return;

	function lockField($el, hintText) {
		if (!$el || !$el.length) return;
		$el.each(function () {
			var $i = jQuery(this);
			// readonly keeps value submitted; disabled would drop it.
			$i.prop('readonly', true).attr('readonly', 'readonly');
			$i.addClass('misa-auto-locked');
			$i.css({
				'background': '#f7f7f7',
				'cursor': 'not-allowed'
			});
			if (!$i.attr('title')) {
				$i.attr('title', hintText);
			}
			// Add inline hint (once)
			var $cell = $i.closest('td');
			if ($cell.length && !$cell.find('.js-auto-generated-hint').length) {
				$cell.append('<div class="js-auto-generated-hint" style="margin-top:4px;font-size:11px;color:#8a8a8a;">' + hintText + '</div>');
			}
		});
	}

	function init() {
		// Only on Potentials create/edit
		try {
			if (window.app && app.getModuleName && app.getModuleName() !== 'Potentials') return;
			var view = window.app && app.getViewName ? app.getViewName() : '';
			if ((view || '').toLowerCase().indexOf('edit') === -1) {
				// vtiger edit view is "Edit", quick create may differ; still proceed if form exists
			}
		} catch (e) {}

		var $form = jQuery('form[name="EditView"], form#EditView');
		if (!$form.length) return;

		lockField($form.find('[name="potentialname"]'), 'Auto-generated (do not edit)');
		lockField($form.find('[name="cf_859"]'), 'Auto-generated Project Code');
	}

	jQuery(init);
})();

